version: "3"
services:
  consumer:
    build: consumer
    expose:
      - 8080
    depends_on:
      - redis

  producer:
    build: producer
    ports:
      - 8081:8080
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - 9379:6379

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - consumer
      - producer

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - consumer
    ports:
      - "8080:8080"
  
  prometheus-statsD:
    image: prom/statsd-exporter
    container_name: prometheus_statsD_exporter
    ports:
      - 9102:9102
      - 18125:9125
      - 18125:9125/udp
    command:
      - --statsd.mapping-config=/tmp/statsd_mapping.yml
    volumes:
      - ./statsd_mapping.yml:/tmp/statsd_mapping.yml
