scrape_configs:
  - job_name: producer
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["producer:8080"]
  - job_name: consumer
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    dns_sd_configs:
      - names: ["consumer"]
        type: A
        port: 8080
        refresh_interval: 15s
  - job_name: pushgateway
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
  - job_name: prometheusStatsDExporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus-statsD:9102"]
